### ISSUE TITLE
ConcurrentModificationException while returning inventories

### ISSUE THREAD

**Issue by nfacha** [nfacha/ChickenDefender#1]
```java
[14:38:16] [Server thread/INFO]: [CHICKEN-DEFENDER] Returning inventory of EricFidelis
[14:38:16] [Server thread/INFO]: [CHICKEN-DEFENDER] Returning inventory of Dwvid13
[14:38:16] [Server thread/WARN]: [CHICKEN-DEFENDER] Task #6021329 for ChickenDefender v1.0 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911) ~[?:1.8.0_262]
	at java.util.ArrayList$Itr.next(ArrayList.java:861) ~[?:1.8.0_262]
	at com.nunofacha.chickendefender.arenas.Arena.finish(Arena.java:243) ~[?:?]
	at com.nunofacha.chickendefender.arenas.Arena.removePlayer(Arena.java:186) ~[?:?]
	at com.nunofacha.chickendefender.listeners.GlobalListener$1.run(GlobalListener.java:65) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**Comment by nfacha** [comment]
cc @jusobreira
