### ISSUE TITLE
EntityDeathEvent crash

### ISSUE THREAD

**Issue by nfacha** [nfacha/ChickenDefender#2]
```java
[14:32:21] [Server thread/INFO]: [CHICKEN-DEFENDER] Chicken for arena 1 has been killed!
[14:32:21] [Server thread/INFO]: [CHICKEN-DEFENDER] Returning inventory of HeisenBatata
[14:32:21] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ChickenDefender v1.0
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911) ~[?:1.8.0_262]
	at java.util.ArrayList$Itr.next(ArrayList.java:861) ~[?:1.8.0_262]
	at com.nunofacha.chickendefender.arenas.Arena.finish(Arena.java:243) ~[?:?]
	at com.nunofacha.chickendefender.listeners.GlobalListener.onChickenDeath(GlobalListener.java:37) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1126.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-135]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-135]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-135]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:794) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.EntityLiving.d(EntityLiving.java:1489) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.EntityLiving.die(EntityLiving.java:1417) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1261) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.EntityHuman.attack(EntityHuman.java:1092) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.EntityPlayer.attack(EntityPlayer.java:1862) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2137) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**Comment by nfacha** [comment]
cc @jusobreira

**Comment by nfacha** [comment]
Duplicate of #1 (caused by the same code)
